### ISSUE TITLE
[Bug] 标程 `\n` 被错误替换

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#734] opened 2024-10-01 10:53 UTC
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/f8d6575a-f06c-4d6f-8c27-41301d0d772e)

### 重现步骤

https://www.xmoj.tech/showsource.php?pid=7678&ByUserScript=1

**Comment by boomzero** [comment] 2024-10-01 11:13
Duplicate of https://github.com/XMOJ-Script-dev/XMOJ-bbs/issues/46

Incredibly hard to fix.

**Closed** 2024-10-01 11:14 UTC
Labels: duplicate

**Comment by langningchen** [comment] 2024-10-02 09:02
没仔细看，竟然 dup ......
